aliases:
  //wing: 132^nd^ Virtual Wing
  //617: 617^th^ DAMBUSTERS
  //696: 696^th^ TURNSKINS
  //176: 176^th^ EYES OF THE NORTH
  //23: 23^rd^ ARCTIC FOXES
  //259: 259^th^ POLAR BEARS
  //765: 765^th^ THE DREAD PANTHERS